spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: vkfksekfqlc27!

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties.hibernate:
      default_batch_fetch_size: 100
      format_sql: true
      show_sql: true

logging.level:
  org.hibernate.SQL: debug